blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^all_posts', views.all_posts, name='all_posts'),
    url(r'^about', views.about, name='about'),
    url(r'^contact', views.contact, name='contact'),
    url(r'^send_contact', views.send_contact, name='send_contact'),
    url(r'^posts/(?P<post_url>\w+-?\w*)/send_comment', views.send_comment, name='send_comment'),
    url(r'^send_answer_to_comment/(?P<post_url>\w+-?\w*)/(?P<comment_id>[0-9]+)/', views.send_answer_to_comment, name='send_answer_to_comment'),
    url(r'^posts/(?P<post_url>\w+-?\w*)/$', views.detail, name='detail'),
    url(r'^login', views.login, name='login'),
    url(r'^auth', views.auth, name='auth'),
    url(r'^sign_in', views.sign_in, name='sign_in'),
    url(r'^logout', views.logout, name='logout'),
    url(r'^forgot_password', views.forgot_password, name='forgot_password'),
    url(r'^(?P<category_id>[0-9]+)/posts_by_category', views.posts_by_category, name='posts_by_category'),
    url(r'^rescue_password', views.rescue_password, name='rescue_password'),
    url(r'^account_confirmation', views.account_confirmation, name='account_confirmation'),
    url(r'^find_post_by_content', views.find_post_by_content, name='find_post_by_content'),
]

"""
ex: /polls/5/
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
"""

learn_django/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .settings import *

js_info_dict = {
    'packages': ('blog',)
}

urlpatterns = [
    url(r'^', include('blog.urls', namespace='blog')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                 {'document_root': MEDIA_ROOT}),
    url(r'^jsi8n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
    url(r'^ckeditor/', include('ckeditor.urls'))
]

blog/models.py
import string
import json

from django.db import models
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from ckeditor.fields import RichTextField
from blog.elastic import ElasticSearchClient
from blog.elastic import DocumentType

fs = FileSystemStorage(location='/media/photos')


# Create your models here.

class Category(models.Model):
	name = models.CharField(max_length=100)

	def __unicode__(self):
		return self.name


class Author(models.Model):
	name = models.CharField(max_length=200)
	email = models.CharField(max_length=200)
	personal_page = models.CharField(max_length=2000, blank=True, null=True)

	def __unicode__(self):
		return self.name


class Post(models.Model):
	title = models.CharField(max_length=200)
	resume = models.CharField(max_length=200)
	text =RichTextField()
	date = models.DateTimeField('date published')
	thumbnail = models.ImageField(upload_to='posts')
	category = models.ForeignKey(Category, blank=False, null=False)
	authors = models.ManyToManyField(Author, blank=False, null=False)
	url = models.CharField(max_length=200, blank=False, null=False)

	def __unicode__(self):
		return self.title


class UserProfile(models.Model):
	user = models.OneToOneField(User, primary_key=True)
	photo = models.ImageField(upload_to='users', blank=True, null=True)

	def __unicode__(self):
		return self.user.first_name


class Comment(models.Model):
	text = models.CharField(max_length=8000)
	date = models.DateTimeField('date creation')
	author = models.ForeignKey(UserProfile, blank=True, null=True)
	post = models.ForeignKey(Post, blank=True, null=True)
	answer_to = models.ForeignKey('self', blank=True, null=True)

	def __unicode__(self):
		return self.text


class Contact(models.Model):
	name = models.CharField(max_length=200)
	email = models.CharField(max_length=200)
	message = models.CharField(max_length=8000)
	creation_date = models.DateTimeField('date creation')
	is_email_sent = models.BooleanField(default=False)

	def __unicode__(self):
		return self.name

	def get_contact_email_message(self):
		return """
			From: {0}
			Email: {1}
			Date: {2}
			Message: {3}
		""".format(self.name.encode('utf-8'), self.email, self.creation_date, self.message.encode('utf-8'))


class TokenPassword(models.Model):
	user = models.ForeignKey(User)
	value = models.CharField(max_length=20)
	is_used = models.BooleanField(default=False)
	used_at = models.DateTimeField('date creation',blank=True, null=True)


class TokenUserSignIn(models.Model):
	user = models.ForeignKey(User)
	value = models.CharField(max_length=20)
	is_used = models.BooleanField(default=False)
	used_at = models.DateTimeField('date creation',blank=True, null=True)



def import_post_document(sender, instance, **kwargs):
	json_message = json.dumps({
		'id': 	 	"""{0}""".format(instance.id), 
		'title': 	"""{0}""".format(instance.title.encode('utf-8')),
	 	'resume':  	"""{0}""".format(instance.resume.encode('utf-8')), 
	 	'text':  	"""{0}""".format(instance.text.encode('utf-8'))
	 	})
	ElasticSearchClient().insert_document(instance.id, json_message, DocumentType.post)

# register the signal in order to import Post object/document to ElasticSearch
post_save.connect(import_post_document, sender=Post, dispatch_uid="search_import_elastic")

blog/forms.py
from django import forms
from .models import UserProfile
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _

class UserForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('username', 'first_name', 'email', 'password',)
		labels = {
        	'username': _('Username'),
        	'first_name': _('Name'),
        	'email': _('Email'),
        	'password': _('Password'),
		}
	def is_valid(self):
		valid = super(UserForm, self).is_valid()
		if not valid:
			return valid

		user = None
		try:
			user = User.objects.get(username=self.cleaned_data['username'])
		except User.DoesNotExist:
			pass
		if user is not None:
			self._errors['username'] = _('This username is already in use, please choose another one')
			return False

		user_by_email = None
		try:
			user_by_email = User.objects.get(email=self.cleaned_data['email'])
		except User.DoesNotExist:
			pass
		if user_by_email is not None:
			self._errors['email'] = _('This e-mail is already in use, please choose another one')
			return False

		return True

class UserProfileForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = ('photo',)

blog/views.py
#from django.template import RequestContext, loader
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, render_to_response
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.template.context_processors import csrf
from django.contrib.auth import  login as login_auth
from django.contrib.auth import logout as logout_auth
from django.contrib.auth.hashers import  make_password 
from django.contrib.sessions.models import Session
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from django.utils.translation import ugettext as _
from django.conf import settings
from django.db import transaction

from .models import Post
from .models import Category
from .models import Contact
from .models import UserProfile
from .models import Comment
from .models import TokenPassword
from .models import TokenUserSignIn

from .forms import UserProfileForm
from .forms import UserForm

from .utils import utils
from .elastic import ElasticSearchClient

import sys
import re
import tasks
import services

# Create your views here.

#TODO: Implement category list as a tag lib.
def index(request):
    post_list = services.paginate(Post.objects.all().order_by('date'), 5, request.GET.get('page'))
    category_list_parts = utils.divide_list_by_two(Category.objects.all())
    context = {'post_list': post_list, 'category_list_1': category_list_parts["list_1"], 'category_list_2': category_list_parts["list_2"]}
    return render(request, 'blog/index.html', context)

#TODO: Implement category list as a tag lib.
def detail(request, post_url):
    post = Post.objects.get(url=post_url)
    category_list_parts = utils.divide_list_by_two(Category.objects.all())
    context = {'post': post, 'category_list_1': category_list_parts["list_1"], 'category_list_2': category_list_parts["list_2"]}
    return render(request, "blog/post/detail.html", context)
    
    
def all_posts(request):
    post_list = services.paginate(Post.objects.all().order_by('-date'), 6, request.GET.get('page'))
    return render(request, 'blog/post/all_posts.html', {'post_list': post_list})

def posts_by_category(request, category_id):
    post_list = services.paginate(Post.objects.filter(category=category_id).order_by('-date'), 3, request.GET.get('page'))
    category = Category.objects.get(pk=category_id)
    return render(request, 'blog/post/posts_by_category.html', {'post_list': post_list, 'category': category})

def find_post_by_content(request):
    post_list = ElasticSearchClient().search_post_by_match(request.POST.get('term'))
    return render(request, 'blog/post/search_posts.html', {'post_list': post_list})

def contact(request):
    return render(request, 'blog/contact.html')

def about(request):
    return render(request, 'blog/about.html')        

def send_contact(request):
    if request.method == 'GET':
        return HttpResponseRedirect('/contact')
    
    services.send_contact(request.POST.get('name'), request.POST.get('email'), request.POST.get('message'), timezone.now())
    return HttpResponse(200)
        
def forgot_password(request):
    if request.method == 'GET':
        return render(request, 'blog/registration/forgot_password.html')

    try: 
        to_email = request.POST.get('email')
    except Exception as inst:
        return HttpResponse('email', status=500)
    try:
        user = User.objects.get(email=to_email)
    except Exception as inst:
        return HttpResponse('user', status=500)  
    try:
        services.forgot_password(user)
        return HttpResponse(200)    
    except Exception as inst:
        print(inst)
        return HttpResponse("forgot_password_error", status=500)  
        
@transaction.atomic
def rescue_password(request):
    if request.method == 'GET':
        try:
            token_pass = TokenPassword.objects.get(value=request.GET.get('token'), is_used=False)
        except ObjectDoesNotExist as inst:
            return render(request, 'blog/registration/rescue_password.html',  {'invalid_token': True})            
        user = User.objects.get(pk=token_pass.user.id)
        return render(request, 'blog/registration/rescue_password.html',  {'token': token_pass, 'token_user': user}) 
    
    try:
        token = request.POST.get('token')
        user_id = request.POST.get('user_id')
        password = request.POST.get('password_1')
        password_confirmation = request.POST.get('password_2')
    except:
        return HttpResponse("missing_information", status=500)  
    try:
        services.rescue_password(token, user_id, password, password_confirmation)
    except Exception as inst:
        return HttpResponse(inst, status=500)  

    return HttpResponse(200)  
                   

def login(request):
    try:
        next = request.GET.get('next')
    except Exception as inst:
        print (type(inst))
        print ('On login process: {0}'.format(inst))        
    
    next = '/' if next is None else '/posts/{0}/#comment-tab'.format(next.split('/')[2]) 
    return render(request, 'blog/registration/login.html', {'next': next})  

def logout(request):
    logout_auth(request)
    return HttpResponseRedirect('/')

def auth(request):
    if request.method == 'GET':
        return HttpResponseRedirect('/')
    try: 
        services.user_authentication(request, request.POST.get('login-username'), request.POST.get('login-password'))
        return HttpResponseRedirect(request.POST.get('login-next'))
    except Exception as inst:
        return render(request, 'blog/registration/login.html', {'invalidation': _(unicode(inst))})

def sign_in(request):
    try:
        return _sign_in(request)
    except Exception as inst:
        print ('Error on creating user: {0}'.format(inst))
        return render(request, 'blog/registration/sign_in.html', {'error': _('Sorry, an error occurred while creating  your user. Try again later.')})     

@transaction.atomic
def _sign_in(request):
    if request.method == 'GET':
        userProfileForm = UserProfileForm()
        userForm = UserForm()
        return render(request, 'blog/registration/sign_in.html', {'userProfileForm': userProfileForm, 'userForm':userForm})

    userProfileForm = UserProfileForm(request.POST, request.FILES or None)
    userForm = UserForm(request.POST or None)
    
    if not userProfileForm.is_valid() or not userForm.is_valid():
        return render(request, 'blog/registration/sign_in.html', {'userProfileForm': userProfileForm, 'userForm':userForm})
    
    user = userForm.save(commit=False)
    
    if not user.password == request.POST.get('password-confirmation'):
        userForm._errors['password'] = _('Wrong password confirmation')
        return render(request, 'blog/registration/sign_in.html', {'userProfileForm': userProfileForm, 'userForm':userForm})
    
    services.encrypt_user_password(user, user.password)

    user_profile = userProfileForm.save(commit=False)
    user_profile.user = user
    user_profile.save()

    token = services.generate_signin_token(user)
    services.send_signin_email(token, user.email)
    return render(request, 'blog/registration/sign_in.html', {'confirmation': _('Your account has been created, please go to your e-mail to confirm it.')})
        

def account_confirmation(request):
    if request.method == 'GET':
        try:
            context = services.expire_signin_token(request.GET.get('token'))
        except Exception as inst:
            return render(request, 'blog/registration/account_confirmation.html',  {'invalid_token': True})            

        return render(request, 'blog/registration/account_confirmation.html',  context) 

@login_required
def send_comment(request, post_url):
    if request.method == 'GET':
        return HttpResponseRedirect('/posts/{0}/'.format(post_url))
    try:
        services.send_comment(request.user, request.POST.get('comment-text'), Post.objects.get(url=post_url))
        return HttpResponseRedirect('/posts/{0}/#comment-tab'.format(post_url))
    except Exception as inst:
        print ('Error on saving comment information: {0}'.format(inst))
        return HttpResponse(500)    
        

@login_required
def send_answer_to_comment(request, post_url, comment_id):
    if request.method == 'GET':
        return HttpResponseRedirect('/posts/{0}/'.format(post_url))
    try:
        services.send_answer_to_comment(comment_id, request.user, request.POST.get('answer-text-{0}'.format(comment_id)), Post.objects.get(url=post_url))
        return HttpResponseRedirect('/posts/{0}/#comment-tab'.format(post_url))
    except Exception as inst:
        print ('Error on saving answer information: {0}'.format(inst))
        return HttpResponse(500)    
        
        

blog/templates/blog/templates/blog_template.html
{% extends "blog/templates/master.html" %}
{% load i18n %}

<!-- Page Content -->
{% block body %}

<div class="container">     
    <div class="row">
        <!-- Blog Content -->
        <div class="col-md-8">
            {% block content %} 
            <p>
                <label>Please override the block "content" as following: <label>
            </p>    
            <p>
                <p>'{'% block content %} </p>
                <p>Your HTML content here!</p>
                <p>{% endblock %'}'</p>
            </p>    
            {% endblock %}
        </div>
        <!-- Sidebar -->
        <div class="col-md-4">
        {% block sidebar %}
            <!-- Blog Search Well -->
            <div class="well">
                <form action="/find_post_by_content/" method="post" >
                    <h4><strong class="strong-green"> {% trans "Blog Search" %} </strong></h4>
                    <fieldset>
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="{% trans 'Search here' %}" id="term" name="term" required data-validation-required-message="{% trans 'Please enter your search term' %}">
                            <p class="help-block text-danger"></p>
                        </div>
                        <!-- Change this to a button or input when using this as a form -->
                        <button type="submit" class="btn btn-lg btn-primary btn-block"> {% trans "Search" %} </button>
                    </fieldset>
                </form>
            </div>

            <!-- Blog Categories Well -->
            <div class="well">
                <h4><strong class="strong-green"> {% trans "Blog Categories" %} </strong></h4>
                <div class="row">
                    <div class="col-lg-6">
                        <ul class="list-unstyled">
                            {% if category_list_1 %}
                                {% for category in category_list_1 %}
                                    <li><a href="{% url 'blog:posts_by_category' category.id %}">{{ category.name }}</a>
                                    </li>
                                {% endfor %}
                            {% endif %}
                        </ul>
                    </div>
                    <div class="col-lg-6">
                        <ul class="list-unstyled">
                            {% if category_list_2 %}
                                {% for category in category_list_2 %}
                                    <li><a href="{% url 'blog:posts_by_category' category.id %}">{{ category.name }}</a>
                                    </li>
                                {% endfor %}
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>

            <!-- Side Widget Well -->
            <div class="well">
                <h4><strong class="strong-green"> {% trans "Related Contents" %} </strong></h4>
                <p style="text-align: justify;">
                    <ul class="list-unstyled">
                        <li> <a href="https://www.python.org/" target="_blank"> {% trans "Python Official Website" %}  </a> </li>
                        <li> <a href="https://www.djangoproject.com/" target="_blank"> {% trans "Django Official Website" %}  </a> </li>
                        <li> <a href="http://www.djangobrasil.org/" target="_blank"> {% trans "Django Brasil" %}  </a> </li>
                    </ul>
                </p>
            </div>
        {% endblock %}
        </div>

    </div>    
</div>
{% endblock %}   

blog/templates/blog/templates/master.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/blog-home.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/bootstrap.min.css' %}" />
    <link rel="icon" type="image/ico" href="{% static 'blog/images/bulbasaur_icon.gif' %}" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta property="og:image" content="{% static 'blog/images/easydjango.png' %}" />

    <!-- Custom CSS <link rel="stylesheet" type="text/css" href="{% static 'blog/css/clean-blog.min.css' %}" />-->
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/custom.css' %}" />
    

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>   

    <script type="text/javascript" src="{% static 'blog/js/jquery-2.1.4.min.js' %}"></script>

    <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-66183598-1']);
        _gaq.push(['_trackPageview']);
    </script>

    <title>{% block title %}EasyDjango!{% endblock %}</title>
</head>
<body>
	<!-- Header -->
	{% block header %}
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'blog:index' %}">Easy Django</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'blog:about' %}"> {% trans "About" %} </a>
                    </li>
                    <li>
                        <a href="{% url 'blog:all_posts' %}"> {% trans "All Posts" %} </a>
                    </li>
                    <li>
                        <a href="{% url 'blog:contact' %}"> {% trans "Contact" %} </a>
                    </li>
                    <li>
                        {% if user.is_anonymous %} 
                            <a href="{% url 'blog:login' %}"> {% trans "(Log in)" %} </a>
                        {% else %}                                
                            <a href="{% url 'blog:logout' %}"> {{ user }} {% trans "(Log out)" %} </a>
                        {% endif %}                            
                    </li>
                </ul>
            </div>

        </div>
    </nav>
    {% endblock %} 
	
	<!-- Body -->
	{% block body %}
    <div class="container"> 
		<p>
	        <label>Please override the block "body" as following: <label>
	    </p>    
	    <p>
	        <p>'{'% block body %} </p>
	        <p>Your HTML content here!</p>
	        <p>{% endblock %'}'</p>
	    </p>
		
    </div>

    {% endblock %}

	<hr>
    
    <!-- Footer -->
    {% block footer %}
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="https://github.com/marcio704/learn_django" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://br.linkedin.com/in/marcioacs" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://twitter.com/marcio7041" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.facebook.com/marcio.amaralsantiago" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <center><p class="copyright text-muted">Copyright &copy; EasyDjango 2015</p></center>
                    <center><strong><p class="copyright text-muted">Powered by Django Framework</p></strong></center>
                </div>
            </div>
        </div>
    </footer>
    {% endblock %}

    <script type="text/javascript" src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    
    <!-- Custom Theme JavaScript -->
    <script type="text/javascript" src="{% static 'blog/js/clean-blog.js' %}"></script>
    <script type="text/javascript" src="{% url 'django.views.i18n.javascript_catalog' %}"></script>

     <script type="text/javascript">  (function() {
        var ga = document.createElement('script');     ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:'   == document.location.protocol ? 'https://ssl'   : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    </script>
</body>
</html>