blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^all_posts', views.all_posts, name='all_posts'),
    url(r'^about', views.about, name='about'),
    url(r'^contact', views.contact, name='contact'),
    url(r'^send_contact', views.send_contact, name='send_contact'),
    url(r'^posts/(?P<post_url>\w+-?\w*)/send_comment', views.send_comment, name='send_comment'),
    url(r'^send_answer_to_comment/(?P<post_url>\w+-?\w*)/(?P<comment_id>[0-9]+)/', views.send_answer_to_comment, name='send_answer_to_comment'),
    url(r'^posts/(?P<post_url>\w+-?\w*)/$', views.detail, name='detail'),
    url(r'^login', views.login, name='login'),
    url(r'^auth', views.auth, name='auth'),
    url(r'^sign_in', views.sign_in, name='sign_in'),
    url(r'^logout', views.logout, name='logout'),
    url(r'^forgot_password', views.forgot_password, name='forgot_password'),
    url(r'^(?P<category_id>[0-9]+)/posts_by_category', views.posts_by_category, name='posts_by_category'),
    url(r'^rescue_password', views.rescue_password, name='rescue_password'),
    url(r'^account_confirmation', views.account_confirmation, name='account_confirmation'),
    url(r'^find_post_by_content', views.find_post_by_content, name='find_post_by_content'),
]

"""
ex: /polls/5/
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
"""

learn_django/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .settings import *

js_info_dict = {
    'packages': ('blog',)
}

urlpatterns = [
    url(r'^', include('blog.urls', namespace='blog')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                 {'document_root': MEDIA_ROOT}),
    url(r'^jsi8n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
    url(r'^ckeditor/', include('ckeditor.urls'))
]

blog/models.py
import string
import json

from django.db import models
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from ckeditor.fields import RichTextField
from blog.elastic import ElasticSearchClient
from blog.elastic import DocumentType

fs = FileSystemStorage(location='/media/photos')


# Create your models here.

class Category(models.Model):
	name = models.CharField(max_length=100)

	def __unicode__(self):
		return self.name


class Author(models.Model):
	name = models.CharField(max_length=200)
	email = models.CharField(max_length=200)
	personal_page = models.CharField(max_length=2000, blank=True, null=True)

	def __unicode__(self):
		return self.name


class Post(models.Model):
	title = models.CharField(max_length=200)
	resume = models.CharField(max_length=200)
	text =RichTextField()
	date = models.DateTimeField('date published')
	thumbnail = models.ImageField(upload_to='posts')
	category = models.ForeignKey(Category, blank=False, null=False)
	authors = models.ManyToManyField(Author, blank=False, null=False)
	url = models.CharField(max_length=200, blank=False, null=False)

	def __unicode__(self):
		return self.title


class UserProfile(models.Model):
	user = models.OneToOneField(User, primary_key=True)
	photo = models.ImageField(upload_to='users', blank=True, null=True)

	def __unicode__(self):
		return self.user.first_name


class Comment(models.Model):
	text = models.CharField(max_length=8000)
	date = models.DateTimeField('date creation')
	author = models.ForeignKey(UserProfile, blank=True, null=True)
	post = models.ForeignKey(Post, blank=True, null=True)
	answer_to = models.ForeignKey('self', blank=True, null=True)

	def __unicode__(self):
		return self.text


class Contact(models.Model):
	name = models.CharField(max_length=200)
	email = models.CharField(max_length=200)
	message = models.CharField(max_length=8000)
	creation_date = models.DateTimeField('date creation')
	is_email_sent = models.BooleanField(default=False)

	def __unicode__(self):
		return self.name

	def get_contact_email_message(self):
		return """
			From: {0}
			Email: {1}
			Date: {2}
			Message: {3}
		""".format(self.name.encode('utf-8'), self.email, self.creation_date, self.message.encode('utf-8'))


class TokenPassword(models.Model):
	user = models.ForeignKey(User)
	value = models.CharField(max_length=20)
	is_used = models.BooleanField(default=False)
	used_at = models.DateTimeField('date creation',blank=True, null=True)


class TokenUserSignIn(models.Model):
	user = models.ForeignKey(User)
	value = models.CharField(max_length=20)
	is_used = models.BooleanField(default=False)
	used_at = models.DateTimeField('date creation',blank=True, null=True)



def import_post_document(sender, instance, **kwargs):
	json_message = json.dumps({
		'id': 	 	"""{0}""".format(instance.id), 
		'title': 	"""{0}""".format(instance.title.encode('utf-8')),
	 	'resume':  	"""{0}""".format(instance.resume.encode('utf-8')), 
	 	'text':  	"""{0}""".format(instance.text.encode('utf-8'))
	 	})
	ElasticSearchClient().insert_document(instance.id, json_message, DocumentType.post)

# register the signal in order to import Post object/document to ElasticSearch
post_save.connect(import_post_document, sender=Post, dispatch_uid="search_import_elastic")

blog/forms.py
from django import forms
from .models import UserProfile
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _

class UserForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('username', 'first_name', 'email', 'password',)
		labels = {
        	'username': _('Username'),
        	'first_name': _('Name'),
        	'email': _('Email'),
        	'password': _('Password'),
		}
	def is_valid(self):
		valid = super(UserForm, self).is_valid()
		if not valid:
			return valid

		user = None
		try:
			user = User.objects.get(username=self.cleaned_data['username'])
		except User.DoesNotExist:
			pass
		if user is not None:
			self._errors['username'] = _('This username is already in use, please choose another one')
			return False

		user_by_email = None
		try:
			user_by_email = User.objects.get(email=self.cleaned_data['email'])
		except User.DoesNotExist:
			pass
		if user_by_email is not None:
			self._errors['email'] = _('This e-mail is already in use, please choose another one')
			return False

		return True

class UserProfileForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = ('photo',)

blog/views.py
#from django.template import RequestContext, loader
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, render_to_response
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.template.context_processors import csrf
from django.contrib.auth import  login as login_auth
from django.contrib.auth import logout as logout_auth
from django.contrib.auth.hashers import  make_password 
from django.contrib.sessions.models import Session
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from django.utils.translation import ugettext as _
from django.conf import settings
from django.db import transaction

from .models import Post
from .models import Category
from .models import Contact
from .models import UserProfile
from .models import Comment
from .models import TokenPassword
from .models import TokenUserSignIn

from .forms import UserProfileForm
from .forms import UserForm

from .utils import utils
from .elastic import ElasticSearchClient

import sys
import re
import tasks
import services

# Create your views here.

#TODO: Implement category list as a tag lib.
def index(request):
    post_list = services.paginate(Post.objects.all().order_by('date'), 5, request.GET.get('page'))
    category_list_parts = utils.divide_list_by_two(Category.objects.all())
    context = {'post_list': post_list, 'category_list_1': category_list_parts["list_1"], 'category_list_2': category_list_parts["list_2"]}
    return render(request, 'blog/index.html', context)

#TODO: Implement category list as a tag lib.
def detail(request, post_url):
    post = Post.objects.get(url=post_url)
    category_list_parts = utils.divide_list_by_two(Category.objects.all())
    context = {'post': post, 'category_list_1': category_list_parts["list_1"], 'category_list_2': category_list_parts["list_2"]}
    return render(request, "blog/post/detail.html", context)
    
    
def all_posts(request):
    post_list = services.paginate(Post.objects.all().order_by('-date'), 6, request.GET.get('page'))
    return render(request, 'blog/post/all_posts.html', {'post_list': post_list})

def posts_by_category(request, category_id):
    post_list = services.paginate(Post.objects.filter(category=category_id).order_by('-date'), 3, request.GET.get('page'))
    category = Category.objects.get(pk=category_id)
    return render(request, 'blog/post/posts_by_category.html', {'post_list': post_list, 'category': category})

def find_post_by_content(request):
    post_list = ElasticSearchClient().search_post_by_match(request.POST.get('term'))
    return render(request, 'blog/post/search_posts.html', {'post_list': post_list})

def contact(request):
    return render(request, 'blog/contact.html')

def about(request):
    return render(request, 'blog/about.html')        

def send_contact(request):
    if request.method == 'GET':
        return HttpResponseRedirect('/contact')
    
    services.send_contact(request.POST.get('name'), request.POST.get('email'), request.POST.get('message'), timezone.now())
    return HttpResponse(200)
        
def forgot_password(request):
    if request.method == 'GET':
        return render(request, 'blog/registration/forgot_password.html')

    try: 
        to_email = request.POST.get('email')
    except Exception as inst:
        return HttpResponse('email', status=500)
    try:
        user = User.objects.get(email=to_email)
    except Exception as inst:
        return HttpResponse('user', status=500)  
    try:
        services.forgot_password(user)
        return HttpResponse(200)    
    except Exception as inst:
        print(inst)
        return HttpResponse("forgot_password_error", status=500)  
        
@transaction.atomic
def rescue_password(request):
    if request.method == 'GET':
        try:
            token_pass = TokenPassword.objects.get(value=request.GET.get('token'), is_used=False)
        except ObjectDoesNotExist as inst:
            return render(request, 'blog/registration/rescue_password.html',  {'invalid_token': True})            
        user = User.objects.get(pk=token_pass.user.id)
        return render(request, 'blog/registration/rescue_password.html',  {'token': token_pass, 'token_user': user}) 
    
    try:
        token = request.POST.get('token')
        user_id = request.POST.get('user_id')
        password = request.POST.get('password_1')
        password_confirmation = request.POST.get('password_2')
    except:
        return HttpResponse("missing_information", status=500)  
    try:
        services.rescue_password(token, user_id, password, password_confirmation)
    except Exception as inst:
        return HttpResponse(inst, status=500)  

    return HttpResponse(200)  
                   

def login(request):
    try:
        next = request.GET.get('next')
    except Exception as inst:
        print (type(inst))
        print ('On login process: {0}'.format(inst))        
    
    next = '/' if next is None else '/posts/{0}/#comment-tab'.format(next.split('/')[2]) 
    return render(request, 'blog/registration/login.html', {'next': next})  

def logout(request):
    logout_auth(request)
    return HttpResponseRedirect('/')

def auth(request):
    if request.method == 'GET':
        return HttpResponseRedirect('/')
    try: 
        services.user_authentication(request, request.POST.get('login-username'), request.POST.get('login-password'))
        return HttpResponseRedirect(request.POST.get('login-next'))
    except Exception as inst:
        return render(request, 'blog/registration/login.html', {'invalidation': _(unicode(inst))})

def sign_in(request):
    try:
        return _sign_in(request)
    except Exception as inst:
        print ('Error on creating user: {0}'.format(inst))
        return render(request, 'blog/registration/sign_in.html', {'error': _('Sorry, an error occurred while creating  your user. Try again later.')})     

@transaction.atomic
def _sign_in(request):
    if request.method == 'GET':
        userProfileForm = UserProfileForm()
        userForm = UserForm()
        return render(request, 'blog/registration/sign_in.html', {'userProfileForm': userProfileForm, 'userForm':userForm})

    userProfileForm = UserProfileForm(request.POST, request.FILES or None)
    userForm = UserForm(request.POST or None)
    
    if not userProfileForm.is_valid() or not userForm.is_valid():
        return render(request, 'blog/registration/sign_in.html', {'userProfileForm': userProfileForm, 'userForm':userForm})
    
    user = userForm.save(commit=False)
    
    if not user.password == request.POST.get('password-confirmation'):
        userForm._errors['password'] = _('Wrong password confirmation')
        return render(request, 'blog/registration/sign_in.html', {'userProfileForm': userProfileForm, 'userForm':userForm})
    
    services.encrypt_user_password(user, user.password)

    user_profile = userProfileForm.save(commit=False)
    user_profile.user = user
    user_profile.save()

    token = services.generate_signin_token(user)
    services.send_signin_email(token, user.email)
    return render(request, 'blog/registration/sign_in.html', {'confirmation': _('Your account has been created, please go to your e-mail to confirm it.')})
        

def account_confirmation(request):
    if request.method == 'GET':
        try:
            context = services.expire_signin_token(request.GET.get('token'))
        except Exception as inst:
            return render(request, 'blog/registration/account_confirmation.html',  {'invalid_token': True})            

        return render(request, 'blog/registration/account_confirmation.html',  context) 

@login_required
def send_comment(request, post_url):
    if request.method == 'GET':
        return HttpResponseRedirect('/posts/{0}/'.format(post_url))
    try:
        services.send_comment(request.user, request.POST.get('comment-text'), Post.objects.get(url=post_url))
        return HttpResponseRedirect('/posts/{0}/#comment-tab'.format(post_url))
    except Exception as inst:
        print ('Error on saving comment information: {0}'.format(inst))
        return HttpResponse(500)    
        

@login_required
def send_answer_to_comment(request, post_url, comment_id):
    if request.method == 'GET':
        return HttpResponseRedirect('/posts/{0}/'.format(post_url))
    try:
        services.send_answer_to_comment(comment_id, request.user, request.POST.get('answer-text-{0}'.format(comment_id)), Post.objects.get(url=post_url))
        return HttpResponseRedirect('/posts/{0}/#comment-tab'.format(post_url))
    except Exception as inst:
        print ('Error on saving answer information: {0}'.format(inst))
        return HttpResponse(500)    
        
        

blog/templates/blog/post/all_posts.html
{% extends "blog/templates/master.html" %}
{% load i18n %}

<!-- Page Content -->
{% block body %}
<div class="container">            
    <!-- Page Header -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Easy Django!
                <small> {% trans "These are all posts we've written so far. Enjoy!" %} </small>
            </h1>
        </div>
    </div>

    <!-- Projects Row -->
    <div class="row">
    {% if post_list %}
        {% for post in post_list %}
            <div class="col-md-4 portfolio-item">
                <center >
                    <a href="{% url 'blog:detail' post.url %}">
                        <img class="img-responsive" src="{{ post.thumbnail.url }}" alt="" width="180" height="180">
                    </a>
                    <h3>
                        <a href="{% url 'blog:detail' post.url %}">{{ post.name }}</a>
                    </h3>
                    <strong><p style="text-aligment: justify;">{{ post.resume }}</p></strong>
                    {% trans 'From:' %} {{ post.date }}
                </center>
            </div>
        {% endfor %}
        <hr>
    
        <!-- Pagination -->
        <div class="row text-center">
            <div class="col-lg-12">
                <!-- Pager -->
                <ul class="pager">
                    <li class="previous">
                        {% if post_list.has_previous %}
                            <a href="?page={{ post_list.previous_page_number }}"> &larr; {% trans "Newer" %} </a>
                        {% endif %}
                    </li>
                    <li class="next">
                        {% if post_list.has_next %}
                            <a href="?page={{ post_list.next_page_number }}"> {% trans "Older" %}  &rarr; </a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    {% else %}
        {% trans "No posts found yet :(" %}
    {% endif %}
    </div>
</div>
{% endblock %}

blog/templates/blog/post/comments.html
{% if comments %}
	{% for comment in comments %}
		<div class="media">
		    <a class="pull-left" href="#">
		        <img class="media-object not-3d-img" src="{{ comment.author.photo.url }}" alt="" width="100" height="100">
		        <label id="hidden-photo" style="display: none;"> {{ comment.author.photo.url }} </label>
		    </a>
		    <div class="media-body">
		        <h4 class="media-heading"> {{ comment.title }}
		            <small> {{ comment.date }} </small>
		        </h4>
		        {{ comment.text }}
		    </div>
		</div>
	{% endfor %}
{% else %}
	<h4 id="no-comments" class="media-heading"> No comments were left here yet. Be the first to comment!</h4	>
{% endif %}
<div id="new-comment"></div>



<!-- Nested Comment  (TO BE IMPLEMENTED)
<div class="media">
    <a class="pull-left" href="#">
        <img class="media-object" src="http://placehold.it/64x64" alt="">
    </a>
    <div class="media-body">
        <h4 class="media-heading">Start Bootstrap
            <small>August 25, 2014 at 9:30 PM</small>
        </h4>
        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.

        <div class="media">
            <a class="pull-left" href="#">
                <img class="media-object" src="http://placehold.it/64x64" alt="">
            </a>
            <div class="media-body">
                <h4 class="media-heading">Nested Start Bootstrap
                    <small>August 25, 2014 at 9:30 PM</small>
                </h4>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            </div>
        </div>
    </div>
</div> -->

blog/templates/blog/post/detail.html
{% extends "blog/templates/blog_template.html" %}
{% load blog_tags %}
{% load i18n %}

<!-- Blog Post -->
{% block content %}

	<!-- Title -->
	<h1 class="page-header">{{ post.title }}</h1>

	<!-- Author -->
	<p class="lead">
		<strong> {% trans "written by:" %} </strong>
		{% for author in post.authors.all %}
			{% if author.personal_page %}
	            <li><a href="{{ author.personal_page }}">{{ author.name }}</a></li>
	        {% else %}
	            <li><span>{{ author.name }}</span></li>
	        {% endif %}
		{% endfor %}
	</p>
	<hr>

	<!-- Date/Time -->
	<p><span class="glyphicon glyphicon-time"></span> {% trans "Posted on:" %}  {{ post.date }}</p>

	<hr>

	<!-- Preview Image -->
	<center><img class="img-responsive" src="{{ post.thumbnail.url }}" alt=""></center>

	<hr>
	<div id="post-content">
		<!-- Post Content -->
		<p class="lead" style="text-align: justify;">{{ post.text |safe }}</p>

		<hr>

		<!-- Blog Comments -->

		<!-- Comments Form -->
		<div class="well"  id="comment-tab" name="comment-tab">
		    <h4> {% trans "Leave a Comment:" %} </h4>
		    <form action="send_comment/" method="post">
			    <div class="form-group">
			        <textarea id="comment-text" name="comment-text" class="form-control" rows="3" rows="5" class="form-control" placeholder="Comment" required data-validation-required-message="Please enter a comment."></textarea>
			    </div>
			    <div id="comment-success"></div>
		    	<button id="comment-form-btn" name="comment-form-btn" class="btn btn-default"> {% trans "Send:" %} </button>
	    	</form>
		</div>
	</div>
	<hr>
	<!-- Posted Comments -->
	{% show_comments post %}
	<div id="new-comment"></div>
	<hr>

	<a class="btn btn-primary" href="{% url 'blog:index' %}"> {% trans "Return to home page" %} <span class="glyphicon glyphicon-chevron-right"></span></a>
	
	<script type="text/javascript">
		$(document).ready( function() {
			$('#post-content').find('img').addClass('not-3d-img img-responsive');
		});	
	</script>
{% endblock %}

<hr>

blog/templates/blog/post/posts_by_category.html
{% extends "blog/templates/master.html" %}
{% load i18n %}

<!-- Page Content -->
{% block body %}
<div class="container">            
    <!-- Page Header -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Easy Django!
                <small> {% trans "Posts about" %} <strong>{{ category.name }}!</strong></small>
            </h1>
        </div>
    </div>

    <!-- Projects Row -->
    <div class="row">
    {% if post_list %}
        {% for post in post_list %}
            <div class="col-md-4 portfolio-item">
                <center >
                    <a href="{% url 'blog:detail' post.url %}">
                        <img class="img-responsive" src="{{ post.thumbnail.url }}" alt="" width="180" height="180">
                    </a>
                    <h3>
                        <a href="{% url 'blog:detail' post.url %}">{{ post.name }}</a>
                    </h3>
                    <strong><p style="text-aligment: justify;">{{ post.resume }}</p></strong>
                </center>
            </div>
        {% endfor %}
    	<hr>

        <!-- Pagination -->
        <div class="row text-center">
            <div class="col-lg-12">
               <!-- Pager -->
                <ul class="pager">
                    <li class="previous">
                        {% if post_list.has_previous %}
                            <a href="?page={{ post_list.previous_page_number }}"> &larr; {% trans "Newer" %} </a>
                        {% endif %}
                    </li>
                    <li class="next">
                        {% if post_list.has_next %}
                            <a href="?page={{ post_list.next_page_number }}"> {% trans "Older" %}  &rarr; </a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>    
    {% else %}
        {% trans "No posts found for this category :(" %}
    {% endif %}
    </div>
</div>
{% endblock %}

blog/templates/blog/post/search_posts.html
{% extends "blog/templates/master.html" %}
{% load i18n %}

<!-- Page Content -->
{% block body %}
<div class="container">            
    <!-- Page Header -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Easy Django!
                <small> {% trans "Posts found for your search" %} </small>
            </h1>
        </div>
    </div>

    <!-- Projects Row -->
    <div class="row">
    {% if post_list %}
        {% for post in post_list %}
            <div class="col-md-4 portfolio-item">
                <center >
                    <a href="{% url 'blog:detail' post.url %}">
                        <img class="img-responsive" src="{{ post.thumbnail.url }}" alt="" width="180" height="180">
                    </a>
                    <h3>
                        <a href="{% url 'blog:detail' post.url %}">{{ post.title |safe }}</a>
                    </h3>
                    <strong><p style="text-aligment: justify;">{{ post.resume |safe }}</p></strong>
                    {% trans 'From:' %} {{ post.date }}
                    <p style="text-aligment: justify;">...{{ post.text |safe }}...</p>
                </center>
            </div>
        {% endfor %}
        <hr>
    
        <!-- Pagination -->
        <div class="row text-center">
            <div class="col-lg-12">
                <!-- Pager -->
                <ul class="pager">
                    <li class="previous">
                        {% if post_list.has_previous %}
                            <a href="?page={{ post_list.previous_page_number }}"> &larr; {% trans "Newer" %} </a>
                        {% endif %}
                    </li>
                    <li class="next">
                        {% if post_list.has_next %}
                            <a href="?page={{ post_list.next_page_number }}"> {% trans "Older" %}  &rarr; </a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    {% else %}
        {% trans "No posts found yet :(" %}
    {% endif %}
    </div>
</div>
{% endblock %}